[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
chat = "F8NS3dkPenxhREk1fAHB35psLf5b7dT7AHtu1voL8F79"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
# Run `export` after building and syncing keys (`anchor keys sync`)
export = "anchor run export_json && anchor run export_ts"
export_json = "cp ./target/idl/chat.json ./app/solana-chat-frontend/src/anchor/chat_idl.json"
export_ts = "cp ./target/types/chat.ts ./app/solana-chat-frontend/src/anchor/chat.idl.ts"

# It will be run with `anchor run test` but also at the end of `anchor test`
test = "yarn run ts-mocha -p ./tsconfig.json 'tests/chat/**/*.ts'"
