[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
chat = "EQbBHuPvwwpEjckervdPSYzaQp4uumwANJYCUyNz46hF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
export = "cp ./target/types/chat.ts ./app/solana-chat-frontend/src/anchor/chat.idl.ts"
test = "yarn run ts-mocha -p ./tsconfig.json 'tests/**/*.ts'"
