[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
chat = "8Cq5oiMmozifx8ReYc9Eb1z57jS84vPL6D9W64duJ2mv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
export = "anchor run export_json && anchor run export_ts"
export_json = "cp ./target/idl/chat.json ./app/src/anchor/chat_idl.json"
export_ts = "cp ./target/types/chat.ts ./app/src/anchor/chat.idl.ts"
test = "yarn run ts-mocha -p ./tsconfig.json 'tests/chat/**/*.ts'"
